---
- name: Restart rabbitmq container (first node)
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname == groups[service.group]|first
  notify:
    - Waiting for rabbitmq to start on first node
    - Reload rabbitmq definitions 

- name: Waiting for rabbitmq to start on first node
  ignore_errors: yes
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  become: true
  shell: "docker exec {{ service.container_name }} rabbitmqctl wait {{ rabbitmq_pid_file }}"
  when:
    - inventory_hostname == groups[service.group]|first

- name: Restart rabbitmq container (rest of nodes)
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname != groups[service.group]|first
  notify:
    - Waiting for rabbitmq to start (rest of nodes)
    - Reload rabbitmq definitions

- name: Waiting for rabbitmq to start (rest of nodes)
  ignore_errors: yes
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  shell: "docker exec {{ service.container_name }} rabbitmqctl wait {{ rabbitmq_pid_file }}"
  when:
    - inventory_hostname == groups[service.group]|first

- name: Reload rabbitmq definitions
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  shell: "docker exec {{ service.container_name }} rabbitmqadmin import {{ container_config_directory }}/definitions.json"
  when:
    - inventory_hostname == groups[service.group]
